name: DIR
channels:
  - dglteam
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - brotli-python=1.0.9=py38h6a678d5_7
  - ca-certificates=2023.08.22=h06a4308_0
  - cryptography=41.0.3=py38h130f0dd_0
  - dgl-cuda11.3=0.9.1post1=py38_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py38h06a4308_0
  - numpy-base=1.24.3=py38h1e6e340_0
  - openssl=1.1.1w=h7f8727e_0
  - pooch=1.7.0=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alabaster==0.7.13
    - anyio==3.4.0
    - anykeystore==0.2
    - argcomplete==1.12.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - async-generator==1.10
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==21.2.0
    - autopep8==2.0.2
    - babel==2.9.1
    - backcall==0.2.0
    - bayesian-optimization==1.2.0
    - beautifulsoup4==4.11.2
    - bidict==0.21.4
    - bleach==4.1.0
    - cachetools==5.0.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.9
    - chocolate==0.0.2
    - click==8.0.3
    - cloudpickle==2.0.0
    - cmake==3.26.1
    - colorama==0.4.4
    - comm==0.1.3
    - contextlib2==21.6.0
    - cryptacular==1.6.2
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.0
    - deepsnap==0.2.1
    - defusedxml==0.7.1
    - dgl==0.6.1
    - dglgo==0.0.2
    - dill==0.3.6
    - docutils==0.19
    - entrypoints==0.3
    - fastjsonschema==2.16.3
    - filelock==3.4.0
    - fonttools==4.32.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - googledrivedownloader==0.4
    - greenlet==1.1.2
    - grpcio==1.44.0
    - huggingface-hub==0.2.1
    - hupper==1.10.3
    - hyperopt==0.1.2
    - idna==3.3
    - imagesize==1.4.1
    - importlib-metadata==4.9.0
    - importlib-resources==5.4.0
    - ipdb==0.13.9
    - ipykernel==6.22.0
    - ipython==7.30.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - isodate==0.6.1
    - isort==5.12.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json-tricks==3.15.5
    - json5==0.9.6
    - jsonschema==4.3.1
    - jupyter==1.0.0
    - jupyter-client==7.1.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-server==1.13.1
    - jupyterlab==3.2.5
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.9.0
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.3.2
    - lightgbm==3.3.2
    - lit==16.0.0
    - littleutils==0.2.2
    - lxml==4.9.2
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mpmath==1.3.0
    - multidict==6.0.2
    - multiprocess==0.70.14
    - munkres==1.1.4
    - nbclassic==0.5.3
    - nbclient==0.6.3
    - nbconvert==6.5.4
    - nbformat==5.7.3
    - nest-asyncio==1.5.4
    - netlsd==1.0.2
    - nltk==3.8.1
    - notebook==6.4.6
    - notebook-shim==0.2.2
    - numpy==1.21.2
    - numpydoc==1.5.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.1.1
    - ogb==1.3.1
    - olefile==0.46
    - outdated==0.2.1
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pastedeploy==2.1.1
    - patsy==0.5.2
    - pbkdf2==1.3
    - pexpect==4.8.0
    - pgmpy==0.1.11
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pip==23.0.1
    - plaster==1.0
    - plaster-pastedeploy==0.7
    - platformdirs==3.2.0
    - plotly==5.18.0
    - prettytable==3.0.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.1
    - ptyprocess==0.7.0
    - py4j==0.10.9.3
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycairo==1.21.0
    - pycodestyle==2.10.0
    - pydantic==1.10.7
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pyg-lib==0.2.0+pt111cu113
    - pygments==2.10.0
    - pymongo==4.0.1
    - pyparsing==3.0.6
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - python-graphviz==0.19.1
    - python3-openid==3.2.0
    - pythonwebhdfs==0.2.3
    - pytorch-lightning==1.6.1
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.4.1
    - qtpy==2.3.1
    - rdflib==6.0.2
    - rdkit-pypi==2021.9.2
    - regex==2021.11.10
    - reportlab==3.5.68
    - repoze-sendmail==4.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - responses==0.18.0
    - rsa==4.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - sacremoses==0.0.46
    - schema==0.7.5
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - setuptools==67.6.1
    - simplejson==3.17.6
    - six==1.16.0
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - soupsieve==2.4
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.4.35
    - statsmodels==0.13.2
    - sympy==1.11.1
    - tabulate==0.8.9
    - tenacity==8.2.3
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.4.1
    - terminado==0.17.1
    - texttable==1.6.4
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.11.0+cu113
    - torch-cluster==1.6.0
    - torch-geometric==2.0.2
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torchaudio==0.11.0+cu113
    - torchmetrics==0.8.0
    - torchvision==0.12.0+cu113
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.9.0
    - transaction==3.0.1
    - transformers==4.14.1
    - translationstring==1.4
    - triton==2.0.0
    - typeguard==2.13.3
    - typer==0.7.0
    - typing-extensions==4.2.0
    - unicodedata2==14.0.0
    - urllib3==1.26.7
    - velruse==1.1.1
    - venusian==3.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - webob==1.8.7
    - websocket-client==1.2.3
    - websockets==10.1
    - werkzeug==2.1.1
    - wheel==0.37.0
    - widgetsnbextension==3.6.0
    - wtforms==3.0.0
    - wtforms-recaptcha==0.3.2
    - xxhash==3.2.0
    - yacs==0.1.8
    - yarl==1.7.2
    - zipp==3.6.0
    - zope-deprecation==4.4.0
    - zope-interface==5.4.0
    - zope-sqlalchemy==1.6
prefix: /media/ycy/anaconda3/envs/DIR
